#!/bin/bash

pushd $(dirname $0) &>/dev/null

if type "brew"; then
  echo "Installing recommended tools"
  brew install ripgrep fd
fi

echo "Updating vim plugins"
nvim +"lua require('lazy').sync({wait=true})" +qa

echo "Installing fonts"
cp fonts/*.ttf ~/Library/Fonts

popd &>/dev/null
